# 0. /3 three datasets

In [1]:
import pandas as pd
l65_df = pd.read_csv("RT65_words.csv", dtype={'strong_num': str})
hb_df = pd.read_csv("biblehub_hb_en_direct.csv", dtype={'strong_num': str})
strongs_df = pd.read_csv("greek-enh-lxx-apo-OT-blb.csv", dtype={'strong_num': str})
l65_g = l65_df.groupby(["book", "chapter", "verse"])
hb_g = hb_df.groupby(["book", "chapter", "verse"])
strongs_g, hb_g = prepare_grouped(strongs_df, hb_df)

# 1. /3 define mappings hebrew to 1965

## mapping!!

In [2]:
# lv vietturis : ebreju vietturis
l65_to_hb={
('1_chronicles', 5, 27) : ('1_chronicles', 6, 1),
('1_chronicles', 5, 28) : ('1_chronicles', 6, 2),
('1_chronicles', 5, 29) : ('1_chronicles', 6, 3),
('1_chronicles', 5, 30) : ('1_chronicles', 6, 4),
('1_chronicles', 5, 31) : ('1_chronicles', 6, 5),
('1_chronicles', 5, 32) : ('1_chronicles', 6, 6),
('1_chronicles', 5, 33) : ('1_chronicles', 6, 7),
('1_chronicles', 5, 34) : ('1_chronicles', 6, 8),
('1_chronicles', 5, 35) : ('1_chronicles', 6, 9),
('1_chronicles', 5, 36) : ('1_chronicles', 6, 10),
('1_chronicles', 5, 37) : ('1_chronicles', 6, 11),
('1_chronicles', 5, 38) : ('1_chronicles', 6, 12),
('1_chronicles', 5, 39) : ('1_chronicles', 6, 13),
('1_chronicles', 5, 40) : ('1_chronicles', 6, 14),
('1_chronicles', 5, 41) : ('1_chronicles', 6, 15)
}
for i in range(1, 66+1):
    l65_to_hb[('1_chronicles', 6, i)]=('1_chronicles', 6, i+15)

for l, h in zip(range(1, 14+1), range(21, 34+1)):
    l65_to_hb[('1_kings', 5, l)]=('1_kings', 4, h)

for i in range(15, 32+1):
    l65_to_hb[('1_kings', 5, i)]=('1_kings', 5, i-14)



#merge 43 + 44
l65_to_hb_merge = {
    (('1_kings', 22, 43), ('1_kings', 22, 44)): ('1_kings', 22, 43)
}

#now update mapping
for i in range(43, 53+1):
    l65_to_hb[('1_kings', 22, i+1)]=('1_kings', 22, i)
#1 samuel 20:42+
l65_to_hb[('1_samuel', 20, 43)]=('1_samuel', 21, 1)
for i in range(1, 13+1):
    l65_to_hb[('1_samuel', 21, i)]=('1_samuel', 21, i+1)
#14, 15 merged => 14 hebrw
l65_to_hb_merge[(('1_samuel', 21, 14), ('1_samuel', 21, 15))] = ('1_samuel', 21, 15)

#1 samuel 23:28+
l65_to_hb[('1_samuel', 24, 1)] = ('1_samuel', 23, 29)
for i in range(2, 23+1):
    l65_to_hb[('1_samuel', 24, i)]=('1_samuel', 24, i-1)

#2chronicles 2:1
l65_to_hb[('2_chronicles', 1, 18)] = ('2_chronicles', 2, 1)
for i in range(1, 17+1):
    l65_to_hb[('2_chronicles', 2, i)]=('2_chronicles', 2, i+1)

#2chronicles 14:1
l65_to_hb[('2_chronicles', 13, 23)] = ('2_chronicles', 14, 1)
for i in range(1, 14+1):
    l65_to_hb[('2_chronicles', 14, i)]=('2_chronicles', 14, i+1)

#2kings 12:1-21
l65_to_hb[('2_kings', 12, 1)] = ('2_kings', 11, 21)
for i in range(2, 22+1):
    l65_to_hb[('2_kings', 12, i)]=('2_kings', 12, i-1)

In [3]:
#2 sam 18:33
l65_to_hb[('2_samuel', 19, 1)] = ('2_samuel', 18, 33)
for i in range(2, 44+1):
    l65_to_hb[('2_samuel', 19, i)]=('2_samuel', 19, i-1)

#daniel 3
l65_to_hb[('daniel', 3, 31)] = ('daniel', 4, 1)
#obsolote, now merge ir rghtfully updating the map.l65_to_hb[('daniel', 3, 32)] = ('daniel', 4, 2), 3

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1 O T R Ā D I !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# 1 lv verse = 2x heb verses, TODO: SPLIT THEM ON WORD BEING LAST IN 1st part
l65_to_hb_merge[(('daniel', 3, 32), "darījis")] = (('daniel', 4, 2), ('daniel', 4, 3))
for i in range(1, 34+1):
    l65_to_hb[('daniel', 4, i)] = ('daniel', 4, i+3)

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1 O T R Ā D I !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# 1 lv verse = 2x heb verses, TODO: SPLIT THEM ON WORD BEING LAST IN 1st part
l65_to_hb_merge[(('daniel', 5, 30), "nogalināts")] = (('daniel', 5, 30), ('daniel', 5, 31))

l65_to_hb[('deuteronomy', 13, 1)] = ('deuteronomy', 12, 32)
for i in range(2, 19+1):
    l65_to_hb[('deuteronomy', 13, i)]=('deuteronomy', 13, i-1)

l65_to_hb[('deuteronomy', 23, 1)] = ('deuteronomy', 22, 30)
for i in range(2, 26+1):
    l65_to_hb[('deuteronomy', 23, i)]=('deuteronomy', 23, i-1)

l65_to_hb[('deuteronomy', 28, 69)] = ('deuteronomy', 29, 1)
l65_to_hb_merge[(('deuteronomy', 29, 1), ('deuteronomy', 29, 2))]=('deuteronomy', 29, 2)

#ecclesiates
l65_to_hb[('ecclesiastes', 4, 17)] = ('ecclesiastes', 5, 1)
for i in range(1, 19+1):
    l65_to_hb[('ecclesiastes', 5, i)]=('ecclesiastes', 5, i+1)

l65_to_hb[('exodus', 1, 21)] = ('exodus', 1, 22)

l65_to_hb[('exodus', 7, 26)] = ('exodus', 8, 1)
l65_to_hb[('exodus', 7, 27)] = ('exodus', 8, 2)
l65_to_hb[('exodus', 7, 28)] = ('exodus', 8, 3)
l65_to_hb[('exodus', 7, 29)] = ('exodus', 8, 4)
for i in range(1, 28+1):
    l65_to_hb[('exodus', 8, i)]=('exodus', 8, i+4)

l65_to_hb[('exodus', 21, 37)] = ('exodus', 22, 1)
for i in range(1, 30+1):
    l65_to_hb[('exodus', 22, i)]=('exodus', 22, i+1)

In [4]:
#ezekiel
for i in range(45, 49+1):
    l65_to_hb[('ezekiel', 21, i-44)]=('ezekiel', 20, i)
for i in range(6, 37+1):
    l65_to_hb[('ezekiel', 21, i)]=('ezekiel', 21, i-5)

# genesis 3 panti savienoti vienā un izlaista 1 tauta
l65_to_hb_merge[(('genesis', 15, 19), "kadmoniešus", "refajiešus")] = (('genesis', 15, 19), ('genesis', 15, 20), ('genesis', 15, 21))

l65_to_hb_merge[(('genesis', 24, 65),('genesis', 24, 66))] = ('genesis', 24, 65)
for i in range(67, 68+1):
    l65_to_hb[('genesis', 24, i)]=('genesis', 24, i-1)


l65_to_hb[('genesis', 32, 1)]=('genesis', 31, 55)
for i in range(2, 33+1):
    l65_to_hb[('genesis', 32, i)]=('genesis', 32, i-1)

#hosea 1
l65_to_hb[('hosea', 2, 1)] = ('hosea', 1, 10)
l65_to_hb[('hosea', 2, 2)] = ('hosea', 1, 11)
for i in range(3, 25+1):
    l65_to_hb[('hosea', 2, i)]=('hosea', 2, i-2)

l65_to_hb[('hosea', 12, 1)] = ('hosea', 11, 12)
for i in range(2, 15+1):
    l65_to_hb[('hosea', 12, i)]=('hosea', 12, i-1)

l65_to_hb[('hosea', 14, 1)] =('hosea', 13, 16)
for i in range(2, 10+1):
    l65_to_hb[('hosea', 14, i)]=('hosea', 14, i-1)

#isaiah
l65_to_hb[('isaiah', 8, 23)] = ('isaiah', 9, 1)
for i in range(1, 20+1):
    l65_to_hb[('isaiah', 9, i)]=('isaiah', 9, i+1)

l65_to_hb[('jeremiah', 8, 23)] = ('jeremiah', 9, 1)
for i in range(1, 25+1):
    l65_to_hb[('jeremiah', 9, i)]=('jeremiah', 9, i+1)

# job
for i in range(25, 32+1):
    l65_to_hb[('job', 40, i)]=('job', 41, i-24)
for i in range(1, 26+1):
    l65_to_hb[('job', 41, i)]=('job', 41, i+8)
#joel
for i in range(1, 5+1):
    l65_to_hb[('joel', 3, i)]=('joel', 2, i+27)
for i in range(1, 21+1):
    l65_to_hb[('joel', 4, i)]=('joel', 3, i)

#jonah
l65_to_hb[('jonah', 2, 1)] = ('jonah', 1, 17)
for i in range(2, 11+1):
    l65_to_hb[('jonah', 2, i)]=('jonah', 2, i-1)

#leviticus
for i in range(20, 26+1):
    l65_to_hb[('leviticus', 5, i)]=('leviticus', 6, i-19)
for i in range(1, 23+1):
    l65_to_hb[('leviticus', 6, i)]=('leviticus', 6, i+7)

#malachi
for i in range(19, 24+1):
    l65_to_hb[('malachi', 3, i)]=('malachi', 4, i-18)
#malachi 4 in Latvian does not exist!!

#micah
l65_to_hb[('micah', 4, 14)] = ('micah', 5, 1)
for i in range(1, 14+1):
    l65_to_hb[('micah', 5, i)]=('micah', 5, i+1)

#nahum
l65_to_hb[('nahum', 2, 1)] = ('nahum', 1, 15)
for i in range(2, 14+1):
    l65_to_hb[('nahum', 2, i)]=('nahum', 2, i-1)

#nehemiah
l65_to_hb[('nehemiah', 10, 1)] = ('nehemiah', 9, 38)
for i in range(2, 40+1):
    l65_to_hb[('nehemiah', 10, i)]=('nehemiah', 10, i-1)

In [5]:
#numbers
for i in range(36, 50+1):
    l65_to_hb[('numbers', 17, i-35)]=('numbers', 16, i)
for i in range(16, 28+1):
    l65_to_hb[('numbers', 17, i)]=('numbers', 17, i-15)

l65_to_hb[('numbers', 30, 1)] = ('numbers', 29, 40)
for i in range(2, 17+1):
    l65_to_hb[('numbers', 30, i)]=('numbers', 30, i-1)

#psalms
def add_psalms_merging_verse_1_in_1965(chap, maxverse):
    l65_to_hb_merge[(('psalms', chap, 1),('psalms', chap, 2))] = ('psalms', chap, 1)
    for i in range(3, maxverse+1):
        l65_to_hb[('psalms', chap, i)]=('psalms', chap, i-1)
        
add_psalms_merging_verse_1_in_1965(3, 9)
add_psalms_merging_verse_1_in_1965(4, 9)
add_psalms_merging_verse_1_in_1965(5, 13)
add_psalms_merging_verse_1_in_1965(6, 11)
add_psalms_merging_verse_1_in_1965(7, 18)
add_psalms_merging_verse_1_in_1965(8, 10)
add_psalms_merging_verse_1_in_1965(9, 21)
add_psalms_merging_verse_1_in_1965(11, 8)
add_psalms_merging_verse_1_in_1965(12, 9)
add_psalms_merging_verse_1_in_1965(13, 7)
add_psalms_merging_verse_1_in_1965(18, 51)
add_psalms_merging_verse_1_in_1965(19, 15)
add_psalms_merging_verse_1_in_1965(20, 10)
add_psalms_merging_verse_1_in_1965(21, 14)
add_psalms_merging_verse_1_in_1965(22, 32)
add_psalms_merging_verse_1_in_1965(30, 13)
#so far ok, therefore will leave the rest of psalms as is no check
add_psalms_merging_verse_1_in_1965(31, 25)
add_psalms_merging_verse_1_in_1965(34, 23)
add_psalms_merging_verse_1_in_1965(36, 13)
add_psalms_merging_verse_1_in_1965(38, 23)
add_psalms_merging_verse_1_in_1965(39, 14)
add_psalms_merging_verse_1_in_1965(40, 18)
add_psalms_merging_verse_1_in_1965(41, 14)
add_psalms_merging_verse_1_in_1965(42, 12)
add_psalms_merging_verse_1_in_1965(44, 27)
add_psalms_merging_verse_1_in_1965(45, 18)
add_psalms_merging_verse_1_in_1965(46, 12)
add_psalms_merging_verse_1_in_1965(47, 10)
add_psalms_merging_verse_1_in_1965(48, 15)
add_psalms_merging_verse_1_in_1965(49, 21)
add_psalms_merging_verse_1_in_1965(51, 20)
add_psalms_merging_verse_1_in_1965(51, 21)
add_psalms_merging_verse_1_in_1965(52, 10)
add_psalms_merging_verse_1_in_1965(52, 11)
add_psalms_merging_verse_1_in_1965(53, 7)
add_psalms_merging_verse_1_in_1965(54, 8)
add_psalms_merging_verse_1_in_1965(54, 9)
add_psalms_merging_verse_1_in_1965(55, 24)
add_psalms_merging_verse_1_in_1965(56, 14)
add_psalms_merging_verse_1_in_1965(57, 12)
add_psalms_merging_verse_1_in_1965(58, 12)
add_psalms_merging_verse_1_in_1965(59, 18)
add_psalms_merging_verse_1_in_1965(60, 13)
add_psalms_merging_verse_1_in_1965(60, 14)
add_psalms_merging_verse_1_in_1965(61, 9)
add_psalms_merging_verse_1_in_1965(62, 13)
add_psalms_merging_verse_1_in_1965(63, 12)
add_psalms_merging_verse_1_in_1965(64, 11)
add_psalms_merging_verse_1_in_1965(65, 14)
add_psalms_merging_verse_1_in_1965(67, 8)
add_psalms_merging_verse_1_in_1965(68, 36)
add_psalms_merging_verse_1_in_1965(69, 37)
add_psalms_merging_verse_1_in_1965(70, 6)
add_psalms_merging_verse_1_in_1965(75, 11)
add_psalms_merging_verse_1_in_1965(76, 13)
add_psalms_merging_verse_1_in_1965(77, 21)
add_psalms_merging_verse_1_in_1965(80, 20)
add_psalms_merging_verse_1_in_1965(81, 17)
add_psalms_merging_verse_1_in_1965(83, 19)
add_psalms_merging_verse_1_in_1965(84, 13)
add_psalms_merging_verse_1_in_1965(85, 14)
add_psalms_merging_verse_1_in_1965(88, 19)
add_psalms_merging_verse_1_in_1965(89, 53)
add_psalms_merging_verse_1_in_1965(92, 16)
add_psalms_merging_verse_1_in_1965(102, 29)
add_psalms_merging_verse_1_in_1965(108, 14)
add_psalms_merging_verse_1_in_1965(140, 14)
add_psalms_merging_verse_1_in_1965(142, 8)

#song
l65_to_hb_merge[(('songs', 4, 16),('songs', 4, 17))] = ('songs', 4, 16)
l65_to_hb[('songs', 7, 1)] = ('songs', 6, 13)
for i in range(2, 14+1):
    l65_to_hb[('songs', 7, i)]=('songs', 7, i-1)

#zechariah
for i in range(18, 21+1):
    l65_to_hb[('zechariah', 2, i-17)]=('zechariah', 1, i)
for i in range(5, 17+1):
    l65_to_hb[('zechariah', 2, i)]=('zechariah', 2, i-4)


#found out..
l65_to_hb_merge[(('genesis', 14, 20),('genesis', 14, 21))] = ('genesis', 24, 20)
l65_to_hb[('genesis', 14, 22)]=('genesis', 14, 21)
l65_to_hb_merge[(('genesis', 14, 23), "zeme")]=(('genesis', 14, 22), ('genesis', 14, 23))


# ebreju vietturis : lv vietturis
hb_to_l65 = {v: k for k, v in l65_to_hb.items() if v[0]!= '!'}
hb_to_l65_merge = {v: k for k, v in l65_to_hb_merge.items()}
for k, v in l65_to_hb_merge.items():
    #multiple hebrews to single latvian
    if isinstance(v[1], tuple):
        for resolvedVerse in v:
            #this is case where split string is specified for single latvian verse
            if(isinstance(k[0], tuple) and isinstance(k[1], str)):
                hb_to_l65[resolvedVerse] = ("!"+k[0][0], k[0][1], k[0][2])
                l65_to_hb[k[0]] = ("!", -1, -1)
            #also never happens in current list, what was the reasoning putting else here, "just so that it is"?
            else:
                hb_to_l65[resolvedVerse] = ("!"+k[0], k[1], k[2])
                l65_to_hb[k[0]] = ("!", -1, -1)
#value is single hebrew verse. so if key 2nd is tuple not string then
    elif isinstance(k[1], tuple):
        #where to split the hebrew verse (no case actually in current list!
        if(isinstance(v[0], tuple) and isinstance(v[1], str)):
            for resolvedVerse in k:
                hb_to_l65[resolvedVerse] = ("!"+v[0][0], v[0][1], v[0][2])
                hb_to_l65[v[0]] = ("!", -2, -2)
        #single heb verse maps to multiple lvs, so put pointer mark ! (watch merges instead of direct)
        #and the rest two just placeholders so that they are not misused anywhere as misguiding references
        else:
            for resolvedVerse in k:
                l65_to_hb[resolvedVerse] = ("!"+v[0], v[1], v[2])
            #print(v[0])
            hb_to_l65[v] = ("!", -2, -2)
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IZLAISTS PANTS 1965
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
hb_to_l65[('exodus', 1, 21)] = None

# check missing 65

## check reverse

In [2]:
void_hb_df = None #already checked @ merge_Heb_lxx_enc_1965

## lv not in heb index

In [7]:
rkeyss = sorted(l65_g.groups.keys())
for i, key in enumerate(rkeyss):
    b, chapter, verse = key
    if key not in hb_g.groups.keys() and key not in l65_to_hb.keys():
        print(key)

## heb not in lv (direct)

In [8]:
keyss = sorted(hb_g.groups.keys())
for i, key in enumerate(keyss):
    b, chapter, verse = key
    if key not in l65_g.groups.keys()  and key not in hb_to_l65.keys():
        print(key)

In [9]:
l65_g.groups[list(l65_to_hb.keys())[0]]

Index([238730, 238731, 238732, 238733, 238734, 238735, 238736, 238737], dtype='int64')

In [10]:
l65_g.get_group(list(l65_to_hb.keys())[0])

                book  chapter  verse  word_idx      text
238730  1_chronicles        5     27         0        Un
238731  1_chronicles        5     27         1    Levija
238732  1_chronicles        5     27         2      dēli
238733  1_chronicles        5     27         3      bija
238734  1_chronicles        5     27         4   Geršons
238735  1_chronicles        5     27         5    Kehats
238736  1_chronicles        5     27         6        un
238737  1_chronicles        5     27         7  Merārijs

In [11]:
hb_g.get_group(list(l65_to_hb.values())[0])

,verse,word,form,form_en,strong_num,strong_title,strong_en_title,translit,translit_title,book,chapter
298192,1,0,בְּנֵ֖י,The sons of,1121,"1121: 1) son, grandson, child, member of a gro...",N‑mpc,bə·nê,be·Nei: The sons of -- Occurrence 785 of 1283.,1_chronicles,6
298193,1,1,לֵוִ֑י,Levi,3878,3878: Levi = joined to<BR> 1) the 3rd son of J...,N‑proper‑ms,lê·wî;,le·Vi;: Levi -- Occurrence 26 of 42.,1_chronicles,6
298194,1,2,גֵּרְשׁ֕וֹן,[were] Gershon,1648,1648: Gershon or Gershom = exile<BR> 1) firstb...,N‑proper‑ms,gê·rə·šō·wn,ge·re·Shon: [were] Gershon -- Occurrence 14 of...,1_chronicles,6
298195,1,3,קְהָ֖ת,Kohath,6955,6955: Kohath = assembly<BR> 1) the 2nd of the ...,N‑proper‑ms,qə·hāṯ,ke·Hat: Kohath -- Occurrence 16 of 27.,1_chronicles,6
298196,1,4,וּמְרָרִֽי׃,and Merari,4847,4847: Merari = bitter<BR> 1) the 3rd son of Le...,Conj‑w|N‑proper‑ms,ū·mə·rā·rî.,u·me·ra·Ri.: and Merari -- Occurrence 4 of 6.,1_chronicles,6

# 3. / 3 Save .txts

In [8]:
from collections import defaultdict

all_keys = sorted(hb_g.groups.keys())

chapters_map = defaultdict(list)
for b, c, v in all_keys:
    chapters_map[(b, c)].append((b, c, v))
# 2. Iterējam cauri nodaļām

In [9]:
import unicodedata
def raccs_common(text):
    d = {
        #ord('\N{COMBINING ACUTE ACCENT}'):None,
        ord('’'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('‘'): None,  # LEFT SINGLE QUOTATION MARK
        ord('“'): None,  # LEFT DOUBLE QUOTATION MARK
        ord('”'): None,  # RIGHT DOUBLE QUOTATION MARK
        ord('['): None,  # LEFT SINGLE QUOTATION MARK
        ord(']'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('-'): None,   # HYPHEN-MINUS
        ord('’'): None,   # HYPHEN-MINUS
        ord('⧼'): None,  # LEFT WHITE ANGLE BRACKET
        ord('⧽'): None,  # RIGHT WHITE ANGLE BRACKET
        ord('*'): None,   # ASTERISK
        ord('⇔'): None,  # LEFT RIGHT DOUBLE ARROW
        ord('〉'): None,  # GREATER-THAN SIGN
        ord('〈'): None,  # LESS-THAN SIGN
        ord('‿'): None,  # LOW LINE
        ord('«'): None,  # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('»'): None,  # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('‹'): None,  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
        ord('›'): None,  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
        ord('('): None,  # LEFT PARENTHESIS
        ord(')'): None,  # RIGHT PARENTHESIS
        ord('-') : None,  # HYPHEN-MINUS
        ord(';') : None,  # SEMICOLON
        ord(',') : None,  # comma
        ord('!') : None,  # !
        ord('?') : None,  # ?
        ord('.') : None,  # .
        }
    return unicodedata.normalize('NFD', text).translate(d)

def raccsGK(text):
    d = {
        ord('\N{COMBINING ACUTE ACCENT}'):None,
        0x0300: None,  # COMBINING GRAVE ACCENT
        0x0301: None,  # COMBINING ACUTE ACCENT
        0x0342: None,  # COMBINING GREEK PERISPOMENI
        0x0313: None,  # COMBINING COMMA ABOVE (PSILI)
        0x0314: None,  # COMBINING REVERSED COMMA ABOVE (DASIA)
        0x0308: None,  # COMBINING DIAERESIS
        0x0304: None,  # COMBINING MACRON
        0x0306: None,  # COMBINING BREVE
        0x0323: None,  # COMBINING DOT BELOW
        0x033E: None,  # COMBINING VERTICAL LINE ABOVE
        0x0345: None,  # COMBINING GREEK YPOGEGRAMMENI
        0x0360: None,  # COMBINING TILDE
        0x034F: None,  # COMBINING GRAPHEME JOINER
        0x035C: None,  # COMBINING DOUBLE BREVE
        0x035E: None,  # COMBINING DOUBLE MACRON
        0x037A: None,  # GREEK YPOGEGRAMMENI
        0x1FBD: None,  # GREEK KORONIS
        0x1FBF: None,  # GREEK PSILI
        0x1FBE: None,  # GREEK DASIA
        0x1FFF: None,   # GREEK OXIA
        ord('’'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('‘'): None,  # LEFT SINGLE QUOTATION MARK
        ord('“'): None,  # LEFT DOUBLE QUOTATION MARK
        ord('”'): None,  # RIGHT DOUBLE QUOTATION MARK
        ord('['): None,  # LEFT SINGLE QUOTATION MARK
        ord(']'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('-'): None,   # HYPHEN-MINUS
        ord('’'): None,   # HYPHEN-MINUS
        ord('⧼'): None,  # LEFT WHITE ANGLE BRACKET
        ord('⧽'): None,  # RIGHT WHITE ANGLE BRACKET
        ord('*'): None,   # ASTERISK
        ord('⇔'): None,  # LEFT RIGHT DOUBLE ARROW
        ord('〉'): None,  # GREATER-THAN SIGN
        ord('〈'): None,  # LESS-THAN SIGN
        ord('‿'): None,  # LOW LINE
        ord('«'): None,  # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('»'): None,  # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('‹'): None,  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
        ord('›'): None,  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
        ord('('): None,  # LEFT PARENTHESIS
        ord(')'): None,  # RIGHT PARENTHESIS
# nestrādā .... nooooooooooooooooooooooo
        ord('-') : None,  # HYPHEN-MINUS
        ord(';') : None,  # SEMICOLON
        ord(',') : None,  # comma
        ord('!') : None,  # !
        ord('?') : None,  # ?
        ord('.') : None,  # .
        }
    return unicodedata.normalize('NFD', raccs_common(text)).translate(d)
    
def raccsLV(text):
    d = {
        }
    return unicodedata.normalize('NFD', raccs_common(text)).translate(d)

In [10]:
raccsLV("āēšķžŗaeskzr,;- hohohoho āēĀŠŽŖĢ")

'āēšķžŗaeskzr hohohoho āēĀŠŽŖĢ'

In [11]:
from pathlib import Path
#from tqdm import tqdm
from tqdm.notebook import tqdm
save_path=Path("bible/")
DEBUG_RESULT_VERSES = 0
def split_str_tokened(input_string, tokens):
    result = []
    current_string = input_string
    
    for token in tokens:
        # Atrodam pirmo marķiera parādīšanās vietu
        token_index = current_string.find(token)
        #print(token_index)
        #print(f"::str:: {current_string} \n::token::  {token}")
        # Ja marķieris netiek atrasts, pārtraucam procesu
        if token_index == -1:
            break
            
        # Sadalām virkni: 
        # pirmā daļa līdz marķiera beigām (ieskaitot pašu marķieri)
        # otrā daļa - viss, kas paliek aiz marķiera
        split_pos = token_index + len(token)
        part = current_string[:split_pos]
        current_string = current_string[split_pos:].strip()

        result.append(part)
        

    if current_string:
        result.append(current_string)
    #print(result)
    #print("-"*50)
    #print(tokens)
    return result



# Lietošanas piemērs:
# k = [('book', 1, 1), 'vārds1', 'vārds2']
# split_str_tokened(teksts, [k[i] for i in range(1, len(k))])
#keyss = sorted(hb_g.groups.keys())
#for i, key in enumerate(keyss):
its = chapters_map.items()
lenits = len(its)
for (b, chapter), verses in tqdm(its, desc="chapters", total=len(its), leave=True):
    chapter_content = []
    #print(f"{b} {str(chapter)} ({i+1}/{lenits})")
    for key in tqdm(verses, desc=f"{b} {chapter}", leave=False):
    #[('genesis', 24, 65)]):
    #keyss):
    #[('daniel', 5, 31)]):
    #keyss):
    #[('psalms', 140, 1)]):
    #[('deuteronomy', 29, 2)]):
    #[('genesis', 15, 19)]):
    #[('genesis', 31, 55)]):
    #keyss):
        b, chapter, verse = key
        heb_text = " ".join(hb_g.get_group(key).sort_values("word")["form"].astype(str))
        chapter_dir = save_path / b / str(chapter)
        chapter_dir.mkdir(parents=True, exist_ok=True)
        
        l65_text=""
        if key in hb_to_l65.keys():
            kkey = hb_to_l65[key]
            if(kkey == None):
                l65_text="-"
            else:
                if not kkey[0][0]=="!":
                    l65_text=" ".join(l65_g.get_group(kkey).sort_values("word_idx")["form"].astype(str))
                else:
                    #merge
                    #l65_to_hb_merge[(('genesis', 15, 19), "kadmoniešus", "refajiešus")] = 
                    #(('genesis', 15, 19), ('genesis', 15, 20), ('genesis', 15, 21))
                    ##l65_to_hb_merge[(('deuteronomy', 29, 1), ('deuteronomy', 29, 2))]=('deuteronomy', 29, 2)
                    #print(kkey)
                    nkey = (kkey[0][1:], kkey[1], kkey[2])
                    #print("here")
                    #print(nkey)
                    for k, v in l65_to_hb_merge.items():
                        #merge will ALWAY have at least 2 items in key (either mergable verse Nr2 or splitstring Nr1)
                        if(isinstance(k[1], str) and k[0] == nkey):
                            
                            #case 1: lv verse has multiple hebrw verses in it
                            sstr = " ".join(l65_g.get_group(nkey).sort_values("word_idx")["form"].astype(str))
                            spArr = split_str_tokened(sstr, [k[i] for i in range(1, len(k))])
                            #print(spArr)
                            if(len(spArr) != len(v)):
                                raise Exception (f"could not tokenise properly!!!@ {k} to {v}")
                            for i, vsNm in enumerate(v):
                                if vsNm == key:
                                    l65_text=spArr[i]
                                    break
                            if not l65_text:
                                raise Exception (f"could not find verse part for the {key} at {k} to {v}")
                        elif(v==key):
                            #now this is inverse case of the above, l65 verses should be merged.
                            rslt = []
                            for mrg_verse in k:
                                rslt.append(" ".join(l65_g.get_group(mrg_verse).sort_values("word_idx")["form"].astype(str)))
                            l65_text = " ".join(rslt)
                            break
                    if not  l65_text:
                        raise Exception (f"key not found! {nkey} :: {key}")
        else:
            l65_text=" ".join(l65_g.get_group(key).sort_values("word_idx")["form"].astype(str))
        l65_text    
        if key in strongs_g.groups.keys():
            greek_text = " ".join(strongs_g.get_group(key).sort_values("word")["form"].astype(str))
        else:
            greek_text = "-"
        l65_text = raccsLV(l65_text)
        chapter_content.append(f"{heb_text}\n{greek_text}\n{l65_text}\n")
        if(DEBUG_RESULT_VERSES):
            print(key)
            print(heb_text)
            print(greek_text)
            print(l65_text)
            break
    #file_path.write_text
    file_path = save_path / b / f"{str(chapter)}.txt"
    #print("".join(chapter_content))#, encoding='utf-8')
    file_path.write_text("".join(chapter_content), encoding='utf-8')
    #break

chapters:   0%|          | 0/929 [00:00<?, ?it/s]

1_chronicles 1:   0%|          | 0/54 [00:00<?, ?it/s]

1_chronicles 2:   0%|          | 0/55 [00:00<?, ?it/s]

1_chronicles 3:   0%|          | 0/24 [00:00<?, ?it/s]

1_chronicles 4:   0%|          | 0/43 [00:00<?, ?it/s]

1_chronicles 5:   0%|          | 0/26 [00:00<?, ?it/s]

1_chronicles 6:   0%|          | 0/81 [00:00<?, ?it/s]

1_chronicles 7:   0%|          | 0/40 [00:00<?, ?it/s]

1_chronicles 8:   0%|          | 0/40 [00:00<?, ?it/s]

1_chronicles 9:   0%|          | 0/44 [00:00<?, ?it/s]

1_chronicles 10:   0%|          | 0/14 [00:00<?, ?it/s]

1_chronicles 11:   0%|          | 0/47 [00:00<?, ?it/s]

1_chronicles 12:   0%|          | 0/40 [00:00<?, ?it/s]

1_chronicles 13:   0%|          | 0/14 [00:00<?, ?it/s]

1_chronicles 14:   0%|          | 0/17 [00:00<?, ?it/s]

1_chronicles 15:   0%|          | 0/29 [00:00<?, ?it/s]

1_chronicles 16:   0%|          | 0/43 [00:00<?, ?it/s]

1_chronicles 17:   0%|          | 0/27 [00:00<?, ?it/s]

1_chronicles 18:   0%|          | 0/17 [00:00<?, ?it/s]

1_chronicles 19:   0%|          | 0/19 [00:00<?, ?it/s]

1_chronicles 20:   0%|          | 0/8 [00:00<?, ?it/s]

1_chronicles 21:   0%|          | 0/30 [00:00<?, ?it/s]

1_chronicles 22:   0%|          | 0/19 [00:00<?, ?it/s]

1_chronicles 23:   0%|          | 0/32 [00:00<?, ?it/s]

1_chronicles 24:   0%|          | 0/31 [00:00<?, ?it/s]

1_chronicles 25:   0%|          | 0/31 [00:00<?, ?it/s]

1_chronicles 26:   0%|          | 0/32 [00:00<?, ?it/s]

1_chronicles 27:   0%|          | 0/34 [00:00<?, ?it/s]

1_chronicles 28:   0%|          | 0/21 [00:00<?, ?it/s]

1_chronicles 29:   0%|          | 0/30 [00:00<?, ?it/s]

1_kings 1:   0%|          | 0/53 [00:00<?, ?it/s]

1_kings 2:   0%|          | 0/46 [00:00<?, ?it/s]

1_kings 3:   0%|          | 0/28 [00:00<?, ?it/s]

1_kings 4:   0%|          | 0/34 [00:00<?, ?it/s]

1_kings 5:   0%|          | 0/18 [00:00<?, ?it/s]

1_kings 6:   0%|          | 0/38 [00:00<?, ?it/s]

1_kings 7:   0%|          | 0/51 [00:00<?, ?it/s]

1_kings 8:   0%|          | 0/66 [00:00<?, ?it/s]

1_kings 9:   0%|          | 0/28 [00:00<?, ?it/s]

1_kings 10:   0%|          | 0/29 [00:00<?, ?it/s]

1_kings 11:   0%|          | 0/43 [00:00<?, ?it/s]

1_kings 12:   0%|          | 0/33 [00:00<?, ?it/s]

1_kings 13:   0%|          | 0/34 [00:00<?, ?it/s]

1_kings 14:   0%|          | 0/31 [00:00<?, ?it/s]

1_kings 15:   0%|          | 0/34 [00:00<?, ?it/s]

1_kings 16:   0%|          | 0/34 [00:00<?, ?it/s]

1_kings 17:   0%|          | 0/24 [00:00<?, ?it/s]

1_kings 18:   0%|          | 0/46 [00:00<?, ?it/s]

1_kings 19:   0%|          | 0/21 [00:00<?, ?it/s]

1_kings 20:   0%|          | 0/43 [00:00<?, ?it/s]

1_kings 21:   0%|          | 0/29 [00:00<?, ?it/s]

1_kings 22:   0%|          | 0/53 [00:00<?, ?it/s]

1_samuel 1:   0%|          | 0/28 [00:00<?, ?it/s]

1_samuel 2:   0%|          | 0/36 [00:00<?, ?it/s]

1_samuel 3:   0%|          | 0/21 [00:00<?, ?it/s]

1_samuel 4:   0%|          | 0/22 [00:00<?, ?it/s]

1_samuel 5:   0%|          | 0/12 [00:00<?, ?it/s]

1_samuel 6:   0%|          | 0/21 [00:00<?, ?it/s]

1_samuel 7:   0%|          | 0/17 [00:00<?, ?it/s]

1_samuel 8:   0%|          | 0/22 [00:00<?, ?it/s]

1_samuel 9:   0%|          | 0/27 [00:00<?, ?it/s]

1_samuel 10:   0%|          | 0/27 [00:00<?, ?it/s]

1_samuel 11:   0%|          | 0/15 [00:00<?, ?it/s]

1_samuel 12:   0%|          | 0/25 [00:00<?, ?it/s]

1_samuel 13:   0%|          | 0/23 [00:00<?, ?it/s]

1_samuel 14:   0%|          | 0/52 [00:00<?, ?it/s]

1_samuel 15:   0%|          | 0/35 [00:00<?, ?it/s]

1_samuel 16:   0%|          | 0/23 [00:00<?, ?it/s]

1_samuel 17:   0%|          | 0/58 [00:00<?, ?it/s]

1_samuel 18:   0%|          | 0/30 [00:00<?, ?it/s]

1_samuel 19:   0%|          | 0/24 [00:00<?, ?it/s]

1_samuel 20:   0%|          | 0/42 [00:00<?, ?it/s]

1_samuel 21:   0%|          | 0/15 [00:00<?, ?it/s]

1_samuel 22:   0%|          | 0/23 [00:00<?, ?it/s]

1_samuel 23:   0%|          | 0/29 [00:00<?, ?it/s]

1_samuel 24:   0%|          | 0/22 [00:00<?, ?it/s]

1_samuel 25:   0%|          | 0/44 [00:00<?, ?it/s]

1_samuel 26:   0%|          | 0/25 [00:00<?, ?it/s]

1_samuel 27:   0%|          | 0/12 [00:00<?, ?it/s]

1_samuel 28:   0%|          | 0/25 [00:00<?, ?it/s]

1_samuel 29:   0%|          | 0/11 [00:00<?, ?it/s]

1_samuel 30:   0%|          | 0/31 [00:00<?, ?it/s]

1_samuel 31:   0%|          | 0/13 [00:00<?, ?it/s]

2_chronicles 1:   0%|          | 0/17 [00:00<?, ?it/s]

2_chronicles 2:   0%|          | 0/18 [00:00<?, ?it/s]

2_chronicles 3:   0%|          | 0/17 [00:00<?, ?it/s]

2_chronicles 4:   0%|          | 0/22 [00:00<?, ?it/s]

2_chronicles 5:   0%|          | 0/14 [00:00<?, ?it/s]

2_chronicles 6:   0%|          | 0/42 [00:00<?, ?it/s]

2_chronicles 7:   0%|          | 0/22 [00:00<?, ?it/s]

2_chronicles 8:   0%|          | 0/18 [00:00<?, ?it/s]

2_chronicles 9:   0%|          | 0/31 [00:00<?, ?it/s]

2_chronicles 10:   0%|          | 0/19 [00:00<?, ?it/s]

2_chronicles 11:   0%|          | 0/23 [00:00<?, ?it/s]

2_chronicles 12:   0%|          | 0/16 [00:00<?, ?it/s]

2_chronicles 13:   0%|          | 0/22 [00:00<?, ?it/s]

2_chronicles 14:   0%|          | 0/15 [00:00<?, ?it/s]

2_chronicles 15:   0%|          | 0/19 [00:00<?, ?it/s]

2_chronicles 16:   0%|          | 0/14 [00:00<?, ?it/s]

2_chronicles 17:   0%|          | 0/19 [00:00<?, ?it/s]

2_chronicles 18:   0%|          | 0/34 [00:00<?, ?it/s]

2_chronicles 19:   0%|          | 0/11 [00:00<?, ?it/s]

2_chronicles 20:   0%|          | 0/37 [00:00<?, ?it/s]

2_chronicles 21:   0%|          | 0/20 [00:00<?, ?it/s]

2_chronicles 22:   0%|          | 0/12 [00:00<?, ?it/s]

2_chronicles 23:   0%|          | 0/21 [00:00<?, ?it/s]

2_chronicles 24:   0%|          | 0/27 [00:00<?, ?it/s]

2_chronicles 25:   0%|          | 0/28 [00:00<?, ?it/s]

2_chronicles 26:   0%|          | 0/23 [00:00<?, ?it/s]

2_chronicles 27:   0%|          | 0/9 [00:00<?, ?it/s]

2_chronicles 28:   0%|          | 0/27 [00:00<?, ?it/s]

2_chronicles 29:   0%|          | 0/36 [00:00<?, ?it/s]

2_chronicles 30:   0%|          | 0/27 [00:00<?, ?it/s]

2_chronicles 31:   0%|          | 0/21 [00:00<?, ?it/s]

2_chronicles 32:   0%|          | 0/33 [00:00<?, ?it/s]

2_chronicles 33:   0%|          | 0/25 [00:00<?, ?it/s]

2_chronicles 34:   0%|          | 0/33 [00:00<?, ?it/s]

2_chronicles 35:   0%|          | 0/27 [00:00<?, ?it/s]

2_chronicles 36:   0%|          | 0/23 [00:00<?, ?it/s]

2_kings 1:   0%|          | 0/18 [00:00<?, ?it/s]

2_kings 2:   0%|          | 0/25 [00:00<?, ?it/s]

2_kings 3:   0%|          | 0/27 [00:00<?, ?it/s]

2_kings 4:   0%|          | 0/44 [00:00<?, ?it/s]

2_kings 5:   0%|          | 0/27 [00:00<?, ?it/s]

2_kings 6:   0%|          | 0/33 [00:00<?, ?it/s]

2_kings 7:   0%|          | 0/20 [00:00<?, ?it/s]

2_kings 8:   0%|          | 0/29 [00:00<?, ?it/s]

2_kings 9:   0%|          | 0/37 [00:00<?, ?it/s]

2_kings 10:   0%|          | 0/36 [00:00<?, ?it/s]

2_kings 11:   0%|          | 0/21 [00:00<?, ?it/s]

2_kings 12:   0%|          | 0/21 [00:00<?, ?it/s]

2_kings 13:   0%|          | 0/25 [00:00<?, ?it/s]

2_kings 14:   0%|          | 0/29 [00:00<?, ?it/s]

2_kings 15:   0%|          | 0/38 [00:00<?, ?it/s]

2_kings 16:   0%|          | 0/20 [00:00<?, ?it/s]

2_kings 17:   0%|          | 0/41 [00:00<?, ?it/s]

2_kings 18:   0%|          | 0/37 [00:00<?, ?it/s]

2_kings 19:   0%|          | 0/37 [00:00<?, ?it/s]

2_kings 20:   0%|          | 0/21 [00:00<?, ?it/s]

2_kings 21:   0%|          | 0/26 [00:00<?, ?it/s]

2_kings 22:   0%|          | 0/20 [00:00<?, ?it/s]

2_kings 23:   0%|          | 0/37 [00:00<?, ?it/s]

2_kings 24:   0%|          | 0/20 [00:00<?, ?it/s]

2_kings 25:   0%|          | 0/30 [00:00<?, ?it/s]

2_samuel 1:   0%|          | 0/27 [00:00<?, ?it/s]

2_samuel 2:   0%|          | 0/32 [00:00<?, ?it/s]

2_samuel 3:   0%|          | 0/39 [00:00<?, ?it/s]

2_samuel 4:   0%|          | 0/12 [00:00<?, ?it/s]

2_samuel 5:   0%|          | 0/25 [00:00<?, ?it/s]

2_samuel 6:   0%|          | 0/23 [00:00<?, ?it/s]

2_samuel 7:   0%|          | 0/29 [00:00<?, ?it/s]

2_samuel 8:   0%|          | 0/18 [00:00<?, ?it/s]

2_samuel 9:   0%|          | 0/13 [00:00<?, ?it/s]

2_samuel 10:   0%|          | 0/19 [00:00<?, ?it/s]

2_samuel 11:   0%|          | 0/27 [00:00<?, ?it/s]

2_samuel 12:   0%|          | 0/31 [00:00<?, ?it/s]

2_samuel 13:   0%|          | 0/39 [00:00<?, ?it/s]

2_samuel 14:   0%|          | 0/33 [00:00<?, ?it/s]

2_samuel 15:   0%|          | 0/37 [00:00<?, ?it/s]

2_samuel 16:   0%|          | 0/23 [00:00<?, ?it/s]

2_samuel 17:   0%|          | 0/29 [00:00<?, ?it/s]

2_samuel 18:   0%|          | 0/33 [00:00<?, ?it/s]

2_samuel 19:   0%|          | 0/43 [00:00<?, ?it/s]

2_samuel 20:   0%|          | 0/26 [00:00<?, ?it/s]

2_samuel 21:   0%|          | 0/22 [00:00<?, ?it/s]

2_samuel 22:   0%|          | 0/51 [00:00<?, ?it/s]

2_samuel 23:   0%|          | 0/39 [00:00<?, ?it/s]

2_samuel 24:   0%|          | 0/25 [00:00<?, ?it/s]

amos 1:   0%|          | 0/15 [00:00<?, ?it/s]

amos 2:   0%|          | 0/16 [00:00<?, ?it/s]

amos 3:   0%|          | 0/15 [00:00<?, ?it/s]

amos 4:   0%|          | 0/13 [00:00<?, ?it/s]

amos 5:   0%|          | 0/27 [00:00<?, ?it/s]

amos 6:   0%|          | 0/14 [00:00<?, ?it/s]

amos 7:   0%|          | 0/17 [00:00<?, ?it/s]

amos 8:   0%|          | 0/14 [00:00<?, ?it/s]

amos 9:   0%|          | 0/15 [00:00<?, ?it/s]

daniel 1:   0%|          | 0/21 [00:00<?, ?it/s]

daniel 2:   0%|          | 0/49 [00:00<?, ?it/s]

daniel 3:   0%|          | 0/30 [00:00<?, ?it/s]

daniel 4:   0%|          | 0/37 [00:00<?, ?it/s]

daniel 5:   0%|          | 0/31 [00:00<?, ?it/s]

daniel 6:   0%|          | 0/28 [00:00<?, ?it/s]

daniel 7:   0%|          | 0/28 [00:00<?, ?it/s]

daniel 8:   0%|          | 0/27 [00:00<?, ?it/s]

daniel 9:   0%|          | 0/27 [00:00<?, ?it/s]

daniel 10:   0%|          | 0/21 [00:00<?, ?it/s]

daniel 11:   0%|          | 0/45 [00:00<?, ?it/s]

daniel 12:   0%|          | 0/13 [00:00<?, ?it/s]

deuteronomy 1:   0%|          | 0/46 [00:00<?, ?it/s]

deuteronomy 2:   0%|          | 0/37 [00:00<?, ?it/s]

deuteronomy 3:   0%|          | 0/29 [00:00<?, ?it/s]

deuteronomy 4:   0%|          | 0/49 [00:00<?, ?it/s]

deuteronomy 5:   0%|          | 0/33 [00:00<?, ?it/s]

deuteronomy 6:   0%|          | 0/25 [00:00<?, ?it/s]

deuteronomy 7:   0%|          | 0/26 [00:00<?, ?it/s]

deuteronomy 8:   0%|          | 0/20 [00:00<?, ?it/s]

deuteronomy 9:   0%|          | 0/29 [00:00<?, ?it/s]

deuteronomy 10:   0%|          | 0/22 [00:00<?, ?it/s]

deuteronomy 11:   0%|          | 0/32 [00:00<?, ?it/s]

deuteronomy 12:   0%|          | 0/32 [00:00<?, ?it/s]

deuteronomy 13:   0%|          | 0/18 [00:00<?, ?it/s]

deuteronomy 14:   0%|          | 0/29 [00:00<?, ?it/s]

deuteronomy 15:   0%|          | 0/23 [00:00<?, ?it/s]

deuteronomy 16:   0%|          | 0/22 [00:00<?, ?it/s]

deuteronomy 17:   0%|          | 0/20 [00:00<?, ?it/s]

deuteronomy 18:   0%|          | 0/22 [00:00<?, ?it/s]

deuteronomy 19:   0%|          | 0/21 [00:00<?, ?it/s]

deuteronomy 20:   0%|          | 0/20 [00:00<?, ?it/s]

deuteronomy 21:   0%|          | 0/23 [00:00<?, ?it/s]

deuteronomy 22:   0%|          | 0/30 [00:00<?, ?it/s]

deuteronomy 23:   0%|          | 0/25 [00:00<?, ?it/s]

deuteronomy 24:   0%|          | 0/22 [00:00<?, ?it/s]

deuteronomy 25:   0%|          | 0/19 [00:00<?, ?it/s]

deuteronomy 26:   0%|          | 0/19 [00:00<?, ?it/s]

deuteronomy 27:   0%|          | 0/26 [00:00<?, ?it/s]

deuteronomy 28:   0%|          | 0/68 [00:00<?, ?it/s]

deuteronomy 29:   0%|          | 0/29 [00:00<?, ?it/s]

deuteronomy 30:   0%|          | 0/20 [00:00<?, ?it/s]

deuteronomy 31:   0%|          | 0/30 [00:00<?, ?it/s]

deuteronomy 32:   0%|          | 0/52 [00:00<?, ?it/s]

deuteronomy 33:   0%|          | 0/29 [00:00<?, ?it/s]

deuteronomy 34:   0%|          | 0/12 [00:00<?, ?it/s]

ecclesiastes 1:   0%|          | 0/18 [00:00<?, ?it/s]

ecclesiastes 2:   0%|          | 0/26 [00:00<?, ?it/s]

ecclesiastes 3:   0%|          | 0/22 [00:00<?, ?it/s]

ecclesiastes 4:   0%|          | 0/16 [00:00<?, ?it/s]

ecclesiastes 5:   0%|          | 0/20 [00:00<?, ?it/s]

ecclesiastes 6:   0%|          | 0/12 [00:00<?, ?it/s]

ecclesiastes 7:   0%|          | 0/29 [00:00<?, ?it/s]

ecclesiastes 8:   0%|          | 0/17 [00:00<?, ?it/s]

ecclesiastes 9:   0%|          | 0/18 [00:00<?, ?it/s]

ecclesiastes 10:   0%|          | 0/20 [00:00<?, ?it/s]

ecclesiastes 11:   0%|          | 0/10 [00:00<?, ?it/s]

ecclesiastes 12:   0%|          | 0/14 [00:00<?, ?it/s]

esther 1:   0%|          | 0/22 [00:00<?, ?it/s]

esther 2:   0%|          | 0/23 [00:00<?, ?it/s]

esther 3:   0%|          | 0/15 [00:00<?, ?it/s]

esther 4:   0%|          | 0/17 [00:00<?, ?it/s]

esther 5:   0%|          | 0/14 [00:00<?, ?it/s]

esther 6:   0%|          | 0/14 [00:00<?, ?it/s]

esther 7:   0%|          | 0/10 [00:00<?, ?it/s]

esther 8:   0%|          | 0/17 [00:00<?, ?it/s]

esther 9:   0%|          | 0/32 [00:00<?, ?it/s]

esther 10:   0%|          | 0/3 [00:00<?, ?it/s]

exodus 1:   0%|          | 0/22 [00:00<?, ?it/s]

exodus 2:   0%|          | 0/25 [00:00<?, ?it/s]

exodus 3:   0%|          | 0/22 [00:00<?, ?it/s]

exodus 4:   0%|          | 0/31 [00:00<?, ?it/s]

exodus 5:   0%|          | 0/23 [00:00<?, ?it/s]

exodus 6:   0%|          | 0/30 [00:00<?, ?it/s]

exodus 7:   0%|          | 0/25 [00:00<?, ?it/s]

exodus 8:   0%|          | 0/32 [00:00<?, ?it/s]

exodus 9:   0%|          | 0/35 [00:00<?, ?it/s]

exodus 10:   0%|          | 0/29 [00:00<?, ?it/s]

exodus 11:   0%|          | 0/10 [00:00<?, ?it/s]

exodus 12:   0%|          | 0/51 [00:00<?, ?it/s]

exodus 13:   0%|          | 0/22 [00:00<?, ?it/s]

exodus 14:   0%|          | 0/31 [00:00<?, ?it/s]

exodus 15:   0%|          | 0/27 [00:00<?, ?it/s]

exodus 16:   0%|          | 0/36 [00:00<?, ?it/s]

exodus 17:   0%|          | 0/16 [00:00<?, ?it/s]

exodus 18:   0%|          | 0/27 [00:00<?, ?it/s]

exodus 19:   0%|          | 0/25 [00:00<?, ?it/s]

exodus 20:   0%|          | 0/26 [00:00<?, ?it/s]

exodus 21:   0%|          | 0/36 [00:00<?, ?it/s]

exodus 22:   0%|          | 0/31 [00:00<?, ?it/s]

exodus 23:   0%|          | 0/33 [00:00<?, ?it/s]

exodus 24:   0%|          | 0/18 [00:00<?, ?it/s]

exodus 25:   0%|          | 0/40 [00:00<?, ?it/s]

exodus 26:   0%|          | 0/37 [00:00<?, ?it/s]

exodus 27:   0%|          | 0/21 [00:00<?, ?it/s]

exodus 28:   0%|          | 0/43 [00:00<?, ?it/s]

exodus 29:   0%|          | 0/46 [00:00<?, ?it/s]

exodus 30:   0%|          | 0/38 [00:00<?, ?it/s]

exodus 31:   0%|          | 0/18 [00:00<?, ?it/s]

exodus 32:   0%|          | 0/35 [00:00<?, ?it/s]

exodus 33:   0%|          | 0/23 [00:00<?, ?it/s]

exodus 34:   0%|          | 0/35 [00:00<?, ?it/s]

exodus 35:   0%|          | 0/35 [00:00<?, ?it/s]

exodus 36:   0%|          | 0/38 [00:00<?, ?it/s]

exodus 37:   0%|          | 0/29 [00:00<?, ?it/s]

exodus 38:   0%|          | 0/31 [00:00<?, ?it/s]

exodus 39:   0%|          | 0/43 [00:00<?, ?it/s]

exodus 40:   0%|          | 0/38 [00:00<?, ?it/s]

ezekiel 1:   0%|          | 0/28 [00:00<?, ?it/s]

ezekiel 2:   0%|          | 0/10 [00:00<?, ?it/s]

ezekiel 3:   0%|          | 0/27 [00:00<?, ?it/s]

ezekiel 4:   0%|          | 0/17 [00:00<?, ?it/s]

ezekiel 5:   0%|          | 0/17 [00:00<?, ?it/s]

ezekiel 6:   0%|          | 0/14 [00:00<?, ?it/s]

ezekiel 7:   0%|          | 0/27 [00:00<?, ?it/s]

ezekiel 8:   0%|          | 0/18 [00:00<?, ?it/s]

ezekiel 9:   0%|          | 0/11 [00:00<?, ?it/s]

ezekiel 10:   0%|          | 0/22 [00:00<?, ?it/s]

ezekiel 11:   0%|          | 0/25 [00:00<?, ?it/s]

ezekiel 12:   0%|          | 0/28 [00:00<?, ?it/s]

ezekiel 13:   0%|          | 0/23 [00:00<?, ?it/s]

ezekiel 14:   0%|          | 0/23 [00:00<?, ?it/s]

ezekiel 15:   0%|          | 0/8 [00:00<?, ?it/s]

ezekiel 16:   0%|          | 0/63 [00:00<?, ?it/s]

ezekiel 17:   0%|          | 0/24 [00:00<?, ?it/s]

ezekiel 18:   0%|          | 0/32 [00:00<?, ?it/s]

ezekiel 19:   0%|          | 0/14 [00:00<?, ?it/s]

ezekiel 20:   0%|          | 0/49 [00:00<?, ?it/s]

ezekiel 21:   0%|          | 0/32 [00:00<?, ?it/s]

ezekiel 22:   0%|          | 0/31 [00:00<?, ?it/s]

ezekiel 23:   0%|          | 0/49 [00:00<?, ?it/s]

ezekiel 24:   0%|          | 0/27 [00:00<?, ?it/s]

ezekiel 25:   0%|          | 0/17 [00:00<?, ?it/s]

ezekiel 26:   0%|          | 0/21 [00:00<?, ?it/s]

ezekiel 27:   0%|          | 0/36 [00:00<?, ?it/s]

ezekiel 28:   0%|          | 0/26 [00:00<?, ?it/s]

ezekiel 29:   0%|          | 0/21 [00:00<?, ?it/s]

ezekiel 30:   0%|          | 0/26 [00:00<?, ?it/s]

ezekiel 31:   0%|          | 0/18 [00:00<?, ?it/s]

ezekiel 32:   0%|          | 0/32 [00:00<?, ?it/s]

ezekiel 33:   0%|          | 0/33 [00:00<?, ?it/s]

ezekiel 34:   0%|          | 0/31 [00:00<?, ?it/s]

ezekiel 35:   0%|          | 0/15 [00:00<?, ?it/s]

ezekiel 36:   0%|          | 0/38 [00:00<?, ?it/s]

ezekiel 37:   0%|          | 0/28 [00:00<?, ?it/s]

ezekiel 38:   0%|          | 0/23 [00:00<?, ?it/s]

ezekiel 39:   0%|          | 0/29 [00:00<?, ?it/s]

ezekiel 40:   0%|          | 0/49 [00:00<?, ?it/s]

ezekiel 41:   0%|          | 0/26 [00:00<?, ?it/s]

ezekiel 42:   0%|          | 0/20 [00:00<?, ?it/s]

ezekiel 43:   0%|          | 0/27 [00:00<?, ?it/s]

ezekiel 44:   0%|          | 0/31 [00:00<?, ?it/s]

ezekiel 45:   0%|          | 0/25 [00:00<?, ?it/s]

ezekiel 46:   0%|          | 0/24 [00:00<?, ?it/s]

ezekiel 47:   0%|          | 0/23 [00:00<?, ?it/s]

ezekiel 48:   0%|          | 0/35 [00:00<?, ?it/s]

ezra 1:   0%|          | 0/11 [00:00<?, ?it/s]

ezra 2:   0%|          | 0/70 [00:00<?, ?it/s]

ezra 3:   0%|          | 0/13 [00:00<?, ?it/s]

ezra 4:   0%|          | 0/24 [00:00<?, ?it/s]

ezra 5:   0%|          | 0/17 [00:00<?, ?it/s]

ezra 6:   0%|          | 0/22 [00:00<?, ?it/s]

ezra 7:   0%|          | 0/28 [00:00<?, ?it/s]

ezra 8:   0%|          | 0/36 [00:00<?, ?it/s]

ezra 9:   0%|          | 0/15 [00:00<?, ?it/s]

ezra 10:   0%|          | 0/44 [00:00<?, ?it/s]

genesis 1:   0%|          | 0/31 [00:00<?, ?it/s]

genesis 2:   0%|          | 0/25 [00:00<?, ?it/s]

genesis 3:   0%|          | 0/24 [00:00<?, ?it/s]

genesis 4:   0%|          | 0/26 [00:00<?, ?it/s]

genesis 5:   0%|          | 0/32 [00:00<?, ?it/s]

genesis 6:   0%|          | 0/22 [00:00<?, ?it/s]

genesis 7:   0%|          | 0/24 [00:00<?, ?it/s]

genesis 8:   0%|          | 0/22 [00:00<?, ?it/s]

genesis 9:   0%|          | 0/29 [00:00<?, ?it/s]

genesis 10:   0%|          | 0/32 [00:00<?, ?it/s]

genesis 11:   0%|          | 0/32 [00:00<?, ?it/s]

genesis 12:   0%|          | 0/20 [00:00<?, ?it/s]

genesis 13:   0%|          | 0/18 [00:00<?, ?it/s]

genesis 14:   0%|          | 0/24 [00:00<?, ?it/s]

genesis 15:   0%|          | 0/21 [00:00<?, ?it/s]

genesis 16:   0%|          | 0/16 [00:00<?, ?it/s]

genesis 17:   0%|          | 0/27 [00:00<?, ?it/s]

genesis 18:   0%|          | 0/33 [00:00<?, ?it/s]

genesis 19:   0%|          | 0/38 [00:00<?, ?it/s]

genesis 20:   0%|          | 0/18 [00:00<?, ?it/s]

genesis 21:   0%|          | 0/34 [00:00<?, ?it/s]

genesis 22:   0%|          | 0/24 [00:00<?, ?it/s]

genesis 23:   0%|          | 0/20 [00:00<?, ?it/s]

genesis 24:   0%|          | 0/67 [00:00<?, ?it/s]

genesis 25:   0%|          | 0/34 [00:00<?, ?it/s]

genesis 26:   0%|          | 0/35 [00:00<?, ?it/s]

genesis 27:   0%|          | 0/46 [00:00<?, ?it/s]

genesis 28:   0%|          | 0/22 [00:00<?, ?it/s]

genesis 29:   0%|          | 0/35 [00:00<?, ?it/s]

genesis 30:   0%|          | 0/43 [00:00<?, ?it/s]

genesis 31:   0%|          | 0/55 [00:00<?, ?it/s]

genesis 32:   0%|          | 0/32 [00:00<?, ?it/s]

genesis 33:   0%|          | 0/20 [00:00<?, ?it/s]

genesis 34:   0%|          | 0/31 [00:00<?, ?it/s]

genesis 35:   0%|          | 0/29 [00:00<?, ?it/s]

genesis 36:   0%|          | 0/43 [00:00<?, ?it/s]

genesis 37:   0%|          | 0/36 [00:00<?, ?it/s]

genesis 38:   0%|          | 0/30 [00:00<?, ?it/s]

genesis 39:   0%|          | 0/23 [00:00<?, ?it/s]

genesis 40:   0%|          | 0/23 [00:00<?, ?it/s]

genesis 41:   0%|          | 0/57 [00:00<?, ?it/s]

genesis 42:   0%|          | 0/38 [00:00<?, ?it/s]

genesis 43:   0%|          | 0/34 [00:00<?, ?it/s]

genesis 44:   0%|          | 0/34 [00:00<?, ?it/s]

genesis 45:   0%|          | 0/28 [00:00<?, ?it/s]

genesis 46:   0%|          | 0/34 [00:00<?, ?it/s]

genesis 47:   0%|          | 0/31 [00:00<?, ?it/s]

genesis 48:   0%|          | 0/22 [00:00<?, ?it/s]

genesis 49:   0%|          | 0/33 [00:00<?, ?it/s]

genesis 50:   0%|          | 0/26 [00:00<?, ?it/s]

habakkuk 1:   0%|          | 0/17 [00:00<?, ?it/s]

habakkuk 2:   0%|          | 0/20 [00:00<?, ?it/s]

habakkuk 3:   0%|          | 0/19 [00:00<?, ?it/s]

haggai 1:   0%|          | 0/15 [00:00<?, ?it/s]

haggai 2:   0%|          | 0/23 [00:00<?, ?it/s]

hosea 1:   0%|          | 0/11 [00:00<?, ?it/s]

hosea 2:   0%|          | 0/23 [00:00<?, ?it/s]

hosea 3:   0%|          | 0/5 [00:00<?, ?it/s]

hosea 4:   0%|          | 0/19 [00:00<?, ?it/s]

hosea 5:   0%|          | 0/15 [00:00<?, ?it/s]

hosea 6:   0%|          | 0/11 [00:00<?, ?it/s]

hosea 7:   0%|          | 0/16 [00:00<?, ?it/s]

hosea 8:   0%|          | 0/14 [00:00<?, ?it/s]

hosea 9:   0%|          | 0/17 [00:00<?, ?it/s]

hosea 10:   0%|          | 0/15 [00:00<?, ?it/s]

hosea 11:   0%|          | 0/12 [00:00<?, ?it/s]

hosea 12:   0%|          | 0/14 [00:00<?, ?it/s]

hosea 13:   0%|          | 0/16 [00:00<?, ?it/s]

hosea 14:   0%|          | 0/9 [00:00<?, ?it/s]

isaiah 1:   0%|          | 0/31 [00:00<?, ?it/s]

isaiah 2:   0%|          | 0/22 [00:00<?, ?it/s]

isaiah 3:   0%|          | 0/26 [00:00<?, ?it/s]

isaiah 4:   0%|          | 0/6 [00:00<?, ?it/s]

isaiah 5:   0%|          | 0/30 [00:00<?, ?it/s]

isaiah 6:   0%|          | 0/13 [00:00<?, ?it/s]

isaiah 7:   0%|          | 0/25 [00:00<?, ?it/s]

isaiah 8:   0%|          | 0/22 [00:00<?, ?it/s]

isaiah 9:   0%|          | 0/21 [00:00<?, ?it/s]

isaiah 10:   0%|          | 0/34 [00:00<?, ?it/s]

isaiah 11:   0%|          | 0/16 [00:00<?, ?it/s]

isaiah 12:   0%|          | 0/6 [00:00<?, ?it/s]

isaiah 13:   0%|          | 0/22 [00:00<?, ?it/s]

isaiah 14:   0%|          | 0/32 [00:00<?, ?it/s]

isaiah 15:   0%|          | 0/9 [00:00<?, ?it/s]

isaiah 16:   0%|          | 0/14 [00:00<?, ?it/s]

isaiah 17:   0%|          | 0/14 [00:00<?, ?it/s]

isaiah 18:   0%|          | 0/7 [00:00<?, ?it/s]

isaiah 19:   0%|          | 0/25 [00:00<?, ?it/s]

isaiah 20:   0%|          | 0/6 [00:00<?, ?it/s]

isaiah 21:   0%|          | 0/17 [00:00<?, ?it/s]

isaiah 22:   0%|          | 0/25 [00:00<?, ?it/s]

isaiah 23:   0%|          | 0/18 [00:00<?, ?it/s]

isaiah 24:   0%|          | 0/23 [00:00<?, ?it/s]

isaiah 25:   0%|          | 0/12 [00:00<?, ?it/s]

isaiah 26:   0%|          | 0/21 [00:00<?, ?it/s]

isaiah 27:   0%|          | 0/13 [00:00<?, ?it/s]

isaiah 28:   0%|          | 0/29 [00:00<?, ?it/s]

isaiah 29:   0%|          | 0/24 [00:00<?, ?it/s]

isaiah 30:   0%|          | 0/33 [00:00<?, ?it/s]

isaiah 31:   0%|          | 0/9 [00:00<?, ?it/s]

isaiah 32:   0%|          | 0/20 [00:00<?, ?it/s]

isaiah 33:   0%|          | 0/24 [00:00<?, ?it/s]

isaiah 34:   0%|          | 0/17 [00:00<?, ?it/s]

isaiah 35:   0%|          | 0/10 [00:00<?, ?it/s]

isaiah 36:   0%|          | 0/22 [00:00<?, ?it/s]

isaiah 37:   0%|          | 0/38 [00:00<?, ?it/s]

isaiah 38:   0%|          | 0/22 [00:00<?, ?it/s]

isaiah 39:   0%|          | 0/8 [00:00<?, ?it/s]

isaiah 40:   0%|          | 0/31 [00:00<?, ?it/s]

isaiah 41:   0%|          | 0/29 [00:00<?, ?it/s]

isaiah 42:   0%|          | 0/25 [00:00<?, ?it/s]

isaiah 43:   0%|          | 0/28 [00:00<?, ?it/s]

isaiah 44:   0%|          | 0/28 [00:00<?, ?it/s]

isaiah 45:   0%|          | 0/25 [00:00<?, ?it/s]

isaiah 46:   0%|          | 0/13 [00:00<?, ?it/s]

isaiah 47:   0%|          | 0/15 [00:00<?, ?it/s]

isaiah 48:   0%|          | 0/22 [00:00<?, ?it/s]

isaiah 49:   0%|          | 0/26 [00:00<?, ?it/s]

isaiah 50:   0%|          | 0/11 [00:00<?, ?it/s]

isaiah 51:   0%|          | 0/23 [00:00<?, ?it/s]

isaiah 52:   0%|          | 0/15 [00:00<?, ?it/s]

isaiah 53:   0%|          | 0/12 [00:00<?, ?it/s]

isaiah 54:   0%|          | 0/17 [00:00<?, ?it/s]

isaiah 55:   0%|          | 0/13 [00:00<?, ?it/s]

isaiah 56:   0%|          | 0/12 [00:00<?, ?it/s]

isaiah 57:   0%|          | 0/21 [00:00<?, ?it/s]

isaiah 58:   0%|          | 0/14 [00:00<?, ?it/s]

isaiah 59:   0%|          | 0/21 [00:00<?, ?it/s]

isaiah 60:   0%|          | 0/22 [00:00<?, ?it/s]

isaiah 61:   0%|          | 0/11 [00:00<?, ?it/s]

isaiah 62:   0%|          | 0/12 [00:00<?, ?it/s]

isaiah 63:   0%|          | 0/19 [00:00<?, ?it/s]

isaiah 64:   0%|          | 0/12 [00:00<?, ?it/s]

isaiah 65:   0%|          | 0/25 [00:00<?, ?it/s]

isaiah 66:   0%|          | 0/24 [00:00<?, ?it/s]

jeremiah 1:   0%|          | 0/19 [00:00<?, ?it/s]

jeremiah 2:   0%|          | 0/37 [00:00<?, ?it/s]

jeremiah 3:   0%|          | 0/25 [00:00<?, ?it/s]

jeremiah 4:   0%|          | 0/31 [00:00<?, ?it/s]

jeremiah 5:   0%|          | 0/31 [00:00<?, ?it/s]

jeremiah 6:   0%|          | 0/30 [00:00<?, ?it/s]

jeremiah 7:   0%|          | 0/34 [00:00<?, ?it/s]

jeremiah 8:   0%|          | 0/22 [00:00<?, ?it/s]

jeremiah 9:   0%|          | 0/26 [00:00<?, ?it/s]

jeremiah 10:   0%|          | 0/25 [00:00<?, ?it/s]

jeremiah 11:   0%|          | 0/23 [00:00<?, ?it/s]

jeremiah 12:   0%|          | 0/17 [00:00<?, ?it/s]

jeremiah 13:   0%|          | 0/27 [00:00<?, ?it/s]

jeremiah 14:   0%|          | 0/22 [00:00<?, ?it/s]

jeremiah 15:   0%|          | 0/21 [00:00<?, ?it/s]

jeremiah 16:   0%|          | 0/21 [00:00<?, ?it/s]

jeremiah 17:   0%|          | 0/27 [00:00<?, ?it/s]

jeremiah 18:   0%|          | 0/23 [00:00<?, ?it/s]

jeremiah 19:   0%|          | 0/15 [00:00<?, ?it/s]

jeremiah 20:   0%|          | 0/18 [00:00<?, ?it/s]

jeremiah 21:   0%|          | 0/14 [00:00<?, ?it/s]

jeremiah 22:   0%|          | 0/30 [00:00<?, ?it/s]

jeremiah 23:   0%|          | 0/40 [00:00<?, ?it/s]

jeremiah 24:   0%|          | 0/10 [00:00<?, ?it/s]

jeremiah 25:   0%|          | 0/38 [00:00<?, ?it/s]

jeremiah 26:   0%|          | 0/24 [00:00<?, ?it/s]

jeremiah 27:   0%|          | 0/22 [00:00<?, ?it/s]

jeremiah 28:   0%|          | 0/17 [00:00<?, ?it/s]

jeremiah 29:   0%|          | 0/32 [00:00<?, ?it/s]

jeremiah 30:   0%|          | 0/24 [00:00<?, ?it/s]

jeremiah 31:   0%|          | 0/40 [00:00<?, ?it/s]

jeremiah 32:   0%|          | 0/44 [00:00<?, ?it/s]

jeremiah 33:   0%|          | 0/26 [00:00<?, ?it/s]

jeremiah 34:   0%|          | 0/22 [00:00<?, ?it/s]

jeremiah 35:   0%|          | 0/19 [00:00<?, ?it/s]

jeremiah 36:   0%|          | 0/32 [00:00<?, ?it/s]

jeremiah 37:   0%|          | 0/21 [00:00<?, ?it/s]

jeremiah 38:   0%|          | 0/28 [00:00<?, ?it/s]

jeremiah 39:   0%|          | 0/18 [00:00<?, ?it/s]

jeremiah 40:   0%|          | 0/16 [00:00<?, ?it/s]

jeremiah 41:   0%|          | 0/18 [00:00<?, ?it/s]

jeremiah 42:   0%|          | 0/22 [00:00<?, ?it/s]

jeremiah 43:   0%|          | 0/13 [00:00<?, ?it/s]

jeremiah 44:   0%|          | 0/30 [00:00<?, ?it/s]

jeremiah 45:   0%|          | 0/5 [00:00<?, ?it/s]

jeremiah 46:   0%|          | 0/28 [00:00<?, ?it/s]

jeremiah 47:   0%|          | 0/7 [00:00<?, ?it/s]

jeremiah 48:   0%|          | 0/47 [00:00<?, ?it/s]

jeremiah 49:   0%|          | 0/39 [00:00<?, ?it/s]

jeremiah 50:   0%|          | 0/46 [00:00<?, ?it/s]

jeremiah 51:   0%|          | 0/64 [00:00<?, ?it/s]

jeremiah 52:   0%|          | 0/34 [00:00<?, ?it/s]

job 1:   0%|          | 0/22 [00:00<?, ?it/s]

job 2:   0%|          | 0/13 [00:00<?, ?it/s]

job 3:   0%|          | 0/26 [00:00<?, ?it/s]

job 4:   0%|          | 0/21 [00:00<?, ?it/s]

job 5:   0%|          | 0/27 [00:00<?, ?it/s]

job 6:   0%|          | 0/30 [00:00<?, ?it/s]

job 7:   0%|          | 0/21 [00:00<?, ?it/s]

job 8:   0%|          | 0/22 [00:00<?, ?it/s]

job 9:   0%|          | 0/35 [00:00<?, ?it/s]

job 10:   0%|          | 0/22 [00:00<?, ?it/s]

job 11:   0%|          | 0/20 [00:00<?, ?it/s]

job 12:   0%|          | 0/25 [00:00<?, ?it/s]

job 13:   0%|          | 0/28 [00:00<?, ?it/s]

job 14:   0%|          | 0/22 [00:00<?, ?it/s]

job 15:   0%|          | 0/35 [00:00<?, ?it/s]

job 16:   0%|          | 0/22 [00:00<?, ?it/s]

job 17:   0%|          | 0/16 [00:00<?, ?it/s]

job 18:   0%|          | 0/21 [00:00<?, ?it/s]

job 19:   0%|          | 0/29 [00:00<?, ?it/s]

job 20:   0%|          | 0/29 [00:00<?, ?it/s]

job 21:   0%|          | 0/34 [00:00<?, ?it/s]

job 22:   0%|          | 0/30 [00:00<?, ?it/s]

job 23:   0%|          | 0/17 [00:00<?, ?it/s]

job 24:   0%|          | 0/25 [00:00<?, ?it/s]

job 25:   0%|          | 0/6 [00:00<?, ?it/s]

job 26:   0%|          | 0/14 [00:00<?, ?it/s]

job 27:   0%|          | 0/23 [00:00<?, ?it/s]

job 28:   0%|          | 0/28 [00:00<?, ?it/s]

job 29:   0%|          | 0/25 [00:00<?, ?it/s]

job 30:   0%|          | 0/31 [00:00<?, ?it/s]

job 31:   0%|          | 0/40 [00:00<?, ?it/s]

job 32:   0%|          | 0/22 [00:00<?, ?it/s]

job 33:   0%|          | 0/33 [00:00<?, ?it/s]

job 34:   0%|          | 0/37 [00:00<?, ?it/s]

job 35:   0%|          | 0/16 [00:00<?, ?it/s]

job 36:   0%|          | 0/33 [00:00<?, ?it/s]

job 37:   0%|          | 0/24 [00:00<?, ?it/s]

job 38:   0%|          | 0/41 [00:00<?, ?it/s]

job 39:   0%|          | 0/30 [00:00<?, ?it/s]

job 40:   0%|          | 0/24 [00:00<?, ?it/s]

job 41:   0%|          | 0/34 [00:00<?, ?it/s]

job 42:   0%|          | 0/17 [00:00<?, ?it/s]

joel 1:   0%|          | 0/20 [00:00<?, ?it/s]

joel 2:   0%|          | 0/32 [00:00<?, ?it/s]

joel 3:   0%|          | 0/21 [00:00<?, ?it/s]

jonah 1:   0%|          | 0/17 [00:00<?, ?it/s]

jonah 2:   0%|          | 0/10 [00:00<?, ?it/s]

jonah 3:   0%|          | 0/10 [00:00<?, ?it/s]

jonah 4:   0%|          | 0/11 [00:00<?, ?it/s]

joshua 1:   0%|          | 0/18 [00:00<?, ?it/s]

joshua 2:   0%|          | 0/24 [00:00<?, ?it/s]

joshua 3:   0%|          | 0/17 [00:00<?, ?it/s]

joshua 4:   0%|          | 0/24 [00:00<?, ?it/s]

joshua 5:   0%|          | 0/15 [00:00<?, ?it/s]

joshua 6:   0%|          | 0/27 [00:00<?, ?it/s]

joshua 7:   0%|          | 0/26 [00:00<?, ?it/s]

joshua 8:   0%|          | 0/35 [00:00<?, ?it/s]

joshua 9:   0%|          | 0/27 [00:00<?, ?it/s]

joshua 10:   0%|          | 0/43 [00:00<?, ?it/s]

joshua 11:   0%|          | 0/23 [00:00<?, ?it/s]

joshua 12:   0%|          | 0/24 [00:00<?, ?it/s]

joshua 13:   0%|          | 0/33 [00:00<?, ?it/s]

joshua 14:   0%|          | 0/15 [00:00<?, ?it/s]

joshua 15:   0%|          | 0/63 [00:00<?, ?it/s]

joshua 16:   0%|          | 0/10 [00:00<?, ?it/s]

joshua 17:   0%|          | 0/18 [00:00<?, ?it/s]

joshua 18:   0%|          | 0/28 [00:00<?, ?it/s]

joshua 19:   0%|          | 0/51 [00:00<?, ?it/s]

joshua 20:   0%|          | 0/9 [00:00<?, ?it/s]

joshua 21:   0%|          | 0/45 [00:00<?, ?it/s]

joshua 22:   0%|          | 0/34 [00:00<?, ?it/s]

joshua 23:   0%|          | 0/16 [00:00<?, ?it/s]

joshua 24:   0%|          | 0/33 [00:00<?, ?it/s]

judges 1:   0%|          | 0/36 [00:00<?, ?it/s]

judges 2:   0%|          | 0/23 [00:00<?, ?it/s]

judges 3:   0%|          | 0/31 [00:00<?, ?it/s]

judges 4:   0%|          | 0/24 [00:00<?, ?it/s]

judges 5:   0%|          | 0/31 [00:00<?, ?it/s]

judges 6:   0%|          | 0/40 [00:00<?, ?it/s]

judges 7:   0%|          | 0/25 [00:00<?, ?it/s]

judges 8:   0%|          | 0/35 [00:00<?, ?it/s]

judges 9:   0%|          | 0/57 [00:00<?, ?it/s]

judges 10:   0%|          | 0/18 [00:00<?, ?it/s]

judges 11:   0%|          | 0/40 [00:00<?, ?it/s]

judges 12:   0%|          | 0/15 [00:00<?, ?it/s]

judges 13:   0%|          | 0/25 [00:00<?, ?it/s]

judges 14:   0%|          | 0/20 [00:00<?, ?it/s]

judges 15:   0%|          | 0/20 [00:00<?, ?it/s]

judges 16:   0%|          | 0/31 [00:00<?, ?it/s]

judges 17:   0%|          | 0/13 [00:00<?, ?it/s]

judges 18:   0%|          | 0/31 [00:00<?, ?it/s]

judges 19:   0%|          | 0/30 [00:00<?, ?it/s]

judges 20:   0%|          | 0/48 [00:00<?, ?it/s]

judges 21:   0%|          | 0/25 [00:00<?, ?it/s]

lamentations 1:   0%|          | 0/22 [00:00<?, ?it/s]

lamentations 2:   0%|          | 0/22 [00:00<?, ?it/s]

lamentations 3:   0%|          | 0/66 [00:00<?, ?it/s]

lamentations 4:   0%|          | 0/22 [00:00<?, ?it/s]

lamentations 5:   0%|          | 0/22 [00:00<?, ?it/s]

leviticus 1:   0%|          | 0/17 [00:00<?, ?it/s]

leviticus 2:   0%|          | 0/16 [00:00<?, ?it/s]

leviticus 3:   0%|          | 0/17 [00:00<?, ?it/s]

leviticus 4:   0%|          | 0/35 [00:00<?, ?it/s]

leviticus 5:   0%|          | 0/19 [00:00<?, ?it/s]

leviticus 6:   0%|          | 0/30 [00:00<?, ?it/s]

leviticus 7:   0%|          | 0/38 [00:00<?, ?it/s]

leviticus 8:   0%|          | 0/36 [00:00<?, ?it/s]

leviticus 9:   0%|          | 0/24 [00:00<?, ?it/s]

leviticus 10:   0%|          | 0/20 [00:00<?, ?it/s]

leviticus 11:   0%|          | 0/47 [00:00<?, ?it/s]

leviticus 12:   0%|          | 0/8 [00:00<?, ?it/s]

leviticus 13:   0%|          | 0/59 [00:00<?, ?it/s]

leviticus 14:   0%|          | 0/57 [00:00<?, ?it/s]

leviticus 15:   0%|          | 0/33 [00:00<?, ?it/s]

leviticus 16:   0%|          | 0/34 [00:00<?, ?it/s]

leviticus 17:   0%|          | 0/16 [00:00<?, ?it/s]

leviticus 18:   0%|          | 0/30 [00:00<?, ?it/s]

leviticus 19:   0%|          | 0/37 [00:00<?, ?it/s]

leviticus 20:   0%|          | 0/27 [00:00<?, ?it/s]

leviticus 21:   0%|          | 0/24 [00:00<?, ?it/s]

leviticus 22:   0%|          | 0/33 [00:00<?, ?it/s]

leviticus 23:   0%|          | 0/44 [00:00<?, ?it/s]

leviticus 24:   0%|          | 0/23 [00:00<?, ?it/s]

leviticus 25:   0%|          | 0/55 [00:00<?, ?it/s]

leviticus 26:   0%|          | 0/46 [00:00<?, ?it/s]

leviticus 27:   0%|          | 0/34 [00:00<?, ?it/s]

malachi 1:   0%|          | 0/14 [00:00<?, ?it/s]

malachi 2:   0%|          | 0/17 [00:00<?, ?it/s]

malachi 3:   0%|          | 0/18 [00:00<?, ?it/s]

malachi 4:   0%|          | 0/6 [00:00<?, ?it/s]

micah 1:   0%|          | 0/16 [00:00<?, ?it/s]

micah 2:   0%|          | 0/13 [00:00<?, ?it/s]

micah 3:   0%|          | 0/12 [00:00<?, ?it/s]

micah 4:   0%|          | 0/13 [00:00<?, ?it/s]

micah 5:   0%|          | 0/15 [00:00<?, ?it/s]

micah 6:   0%|          | 0/16 [00:00<?, ?it/s]

micah 7:   0%|          | 0/20 [00:00<?, ?it/s]

nahum 1:   0%|          | 0/15 [00:00<?, ?it/s]

nahum 2:   0%|          | 0/13 [00:00<?, ?it/s]

nahum 3:   0%|          | 0/19 [00:00<?, ?it/s]

nehemiah 1:   0%|          | 0/11 [00:00<?, ?it/s]

nehemiah 2:   0%|          | 0/20 [00:00<?, ?it/s]

nehemiah 3:   0%|          | 0/32 [00:00<?, ?it/s]

nehemiah 4:   0%|          | 0/23 [00:00<?, ?it/s]

nehemiah 5:   0%|          | 0/19 [00:00<?, ?it/s]

nehemiah 6:   0%|          | 0/19 [00:00<?, ?it/s]

nehemiah 7:   0%|          | 0/73 [00:00<?, ?it/s]

nehemiah 8:   0%|          | 0/18 [00:00<?, ?it/s]

nehemiah 9:   0%|          | 0/38 [00:00<?, ?it/s]

nehemiah 10:   0%|          | 0/39 [00:00<?, ?it/s]

nehemiah 11:   0%|          | 0/36 [00:00<?, ?it/s]

nehemiah 12:   0%|          | 0/47 [00:00<?, ?it/s]

nehemiah 13:   0%|          | 0/31 [00:00<?, ?it/s]

numbers 1:   0%|          | 0/54 [00:00<?, ?it/s]

numbers 2:   0%|          | 0/34 [00:00<?, ?it/s]

numbers 3:   0%|          | 0/51 [00:00<?, ?it/s]

numbers 4:   0%|          | 0/49 [00:00<?, ?it/s]

numbers 5:   0%|          | 0/31 [00:00<?, ?it/s]

numbers 6:   0%|          | 0/27 [00:00<?, ?it/s]

numbers 7:   0%|          | 0/89 [00:00<?, ?it/s]

numbers 8:   0%|          | 0/26 [00:00<?, ?it/s]

numbers 9:   0%|          | 0/23 [00:00<?, ?it/s]

numbers 10:   0%|          | 0/36 [00:00<?, ?it/s]

numbers 11:   0%|          | 0/35 [00:00<?, ?it/s]

numbers 12:   0%|          | 0/16 [00:00<?, ?it/s]

numbers 13:   0%|          | 0/33 [00:00<?, ?it/s]

numbers 14:   0%|          | 0/45 [00:00<?, ?it/s]

numbers 15:   0%|          | 0/41 [00:00<?, ?it/s]

numbers 16:   0%|          | 0/50 [00:00<?, ?it/s]

numbers 17:   0%|          | 0/13 [00:00<?, ?it/s]

numbers 18:   0%|          | 0/32 [00:00<?, ?it/s]

numbers 19:   0%|          | 0/22 [00:00<?, ?it/s]

numbers 20:   0%|          | 0/29 [00:00<?, ?it/s]

numbers 21:   0%|          | 0/35 [00:00<?, ?it/s]

numbers 22:   0%|          | 0/41 [00:00<?, ?it/s]

numbers 23:   0%|          | 0/30 [00:00<?, ?it/s]

numbers 24:   0%|          | 0/25 [00:00<?, ?it/s]

numbers 25:   0%|          | 0/18 [00:00<?, ?it/s]

numbers 26:   0%|          | 0/65 [00:00<?, ?it/s]

numbers 27:   0%|          | 0/23 [00:00<?, ?it/s]

numbers 28:   0%|          | 0/31 [00:00<?, ?it/s]

numbers 29:   0%|          | 0/40 [00:00<?, ?it/s]

numbers 30:   0%|          | 0/16 [00:00<?, ?it/s]

numbers 31:   0%|          | 0/54 [00:00<?, ?it/s]

numbers 32:   0%|          | 0/42 [00:00<?, ?it/s]

numbers 33:   0%|          | 0/56 [00:00<?, ?it/s]

numbers 34:   0%|          | 0/29 [00:00<?, ?it/s]

numbers 35:   0%|          | 0/34 [00:00<?, ?it/s]

numbers 36:   0%|          | 0/13 [00:00<?, ?it/s]

obadiah 1:   0%|          | 0/21 [00:00<?, ?it/s]

proverbs 1:   0%|          | 0/33 [00:00<?, ?it/s]

proverbs 2:   0%|          | 0/22 [00:00<?, ?it/s]

proverbs 3:   0%|          | 0/35 [00:00<?, ?it/s]

proverbs 4:   0%|          | 0/27 [00:00<?, ?it/s]

proverbs 5:   0%|          | 0/23 [00:00<?, ?it/s]

proverbs 6:   0%|          | 0/35 [00:00<?, ?it/s]

proverbs 7:   0%|          | 0/27 [00:00<?, ?it/s]

proverbs 8:   0%|          | 0/36 [00:00<?, ?it/s]

proverbs 9:   0%|          | 0/18 [00:00<?, ?it/s]

proverbs 10:   0%|          | 0/32 [00:00<?, ?it/s]

proverbs 11:   0%|          | 0/31 [00:00<?, ?it/s]

proverbs 12:   0%|          | 0/28 [00:00<?, ?it/s]

proverbs 13:   0%|          | 0/25 [00:00<?, ?it/s]

proverbs 14:   0%|          | 0/35 [00:00<?, ?it/s]

proverbs 15:   0%|          | 0/33 [00:00<?, ?it/s]

proverbs 16:   0%|          | 0/33 [00:00<?, ?it/s]

proverbs 17:   0%|          | 0/28 [00:00<?, ?it/s]

proverbs 18:   0%|          | 0/24 [00:00<?, ?it/s]

proverbs 19:   0%|          | 0/29 [00:00<?, ?it/s]

proverbs 20:   0%|          | 0/30 [00:00<?, ?it/s]

proverbs 21:   0%|          | 0/31 [00:00<?, ?it/s]

proverbs 22:   0%|          | 0/29 [00:00<?, ?it/s]

proverbs 23:   0%|          | 0/35 [00:00<?, ?it/s]

proverbs 24:   0%|          | 0/34 [00:00<?, ?it/s]

proverbs 25:   0%|          | 0/28 [00:00<?, ?it/s]

proverbs 26:   0%|          | 0/28 [00:00<?, ?it/s]

proverbs 27:   0%|          | 0/27 [00:00<?, ?it/s]

proverbs 28:   0%|          | 0/28 [00:00<?, ?it/s]

proverbs 29:   0%|          | 0/27 [00:00<?, ?it/s]

proverbs 30:   0%|          | 0/33 [00:00<?, ?it/s]

proverbs 31:   0%|          | 0/31 [00:00<?, ?it/s]

psalms 1:   0%|          | 0/6 [00:00<?, ?it/s]

psalms 2:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 3:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 4:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 5:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 6:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 7:   0%|          | 0/17 [00:00<?, ?it/s]

psalms 8:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 9:   0%|          | 0/20 [00:00<?, ?it/s]

psalms 10:   0%|          | 0/18 [00:00<?, ?it/s]

psalms 11:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 12:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 13:   0%|          | 0/6 [00:00<?, ?it/s]

psalms 14:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 15:   0%|          | 0/5 [00:00<?, ?it/s]

psalms 16:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 17:   0%|          | 0/15 [00:00<?, ?it/s]

psalms 18:   0%|          | 0/50 [00:00<?, ?it/s]

psalms 19:   0%|          | 0/14 [00:00<?, ?it/s]

psalms 20:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 21:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 22:   0%|          | 0/31 [00:00<?, ?it/s]

psalms 23:   0%|          | 0/6 [00:00<?, ?it/s]

psalms 24:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 25:   0%|          | 0/22 [00:00<?, ?it/s]

psalms 26:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 27:   0%|          | 0/14 [00:00<?, ?it/s]

psalms 28:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 29:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 30:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 31:   0%|          | 0/24 [00:00<?, ?it/s]

psalms 32:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 33:   0%|          | 0/22 [00:00<?, ?it/s]

psalms 34:   0%|          | 0/22 [00:00<?, ?it/s]

psalms 35:   0%|          | 0/28 [00:00<?, ?it/s]

psalms 36:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 37:   0%|          | 0/40 [00:00<?, ?it/s]

psalms 38:   0%|          | 0/22 [00:00<?, ?it/s]

psalms 39:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 40:   0%|          | 0/17 [00:00<?, ?it/s]

psalms 41:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 42:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 43:   0%|          | 0/5 [00:00<?, ?it/s]

psalms 44:   0%|          | 0/26 [00:00<?, ?it/s]

psalms 45:   0%|          | 0/17 [00:00<?, ?it/s]

psalms 46:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 47:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 48:   0%|          | 0/14 [00:00<?, ?it/s]

psalms 49:   0%|          | 0/20 [00:00<?, ?it/s]

psalms 50:   0%|          | 0/23 [00:00<?, ?it/s]

psalms 51:   0%|          | 0/19 [00:00<?, ?it/s]

psalms 52:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 53:   0%|          | 0/6 [00:00<?, ?it/s]

psalms 54:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 55:   0%|          | 0/23 [00:00<?, ?it/s]

psalms 56:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 57:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 58:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 59:   0%|          | 0/17 [00:00<?, ?it/s]

psalms 60:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 61:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 62:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 63:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 64:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 65:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 66:   0%|          | 0/20 [00:00<?, ?it/s]

psalms 67:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 68:   0%|          | 0/35 [00:00<?, ?it/s]

psalms 69:   0%|          | 0/36 [00:00<?, ?it/s]

psalms 70:   0%|          | 0/5 [00:00<?, ?it/s]

psalms 71:   0%|          | 0/24 [00:00<?, ?it/s]

psalms 72:   0%|          | 0/20 [00:00<?, ?it/s]

psalms 73:   0%|          | 0/28 [00:00<?, ?it/s]

psalms 74:   0%|          | 0/23 [00:00<?, ?it/s]

psalms 75:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 76:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 77:   0%|          | 0/20 [00:00<?, ?it/s]

psalms 78:   0%|          | 0/72 [00:00<?, ?it/s]

psalms 79:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 80:   0%|          | 0/19 [00:00<?, ?it/s]

psalms 81:   0%|          | 0/16 [00:00<?, ?it/s]

psalms 82:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 83:   0%|          | 0/18 [00:00<?, ?it/s]

psalms 84:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 85:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 86:   0%|          | 0/17 [00:00<?, ?it/s]

psalms 87:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 88:   0%|          | 0/18 [00:00<?, ?it/s]

psalms 89:   0%|          | 0/52 [00:00<?, ?it/s]

psalms 90:   0%|          | 0/17 [00:00<?, ?it/s]

psalms 91:   0%|          | 0/16 [00:00<?, ?it/s]

psalms 92:   0%|          | 0/15 [00:00<?, ?it/s]

psalms 93:   0%|          | 0/5 [00:00<?, ?it/s]

psalms 94:   0%|          | 0/23 [00:00<?, ?it/s]

psalms 95:   0%|          | 0/11 [00:00<?, ?it/s]

psalms 96:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 97:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 98:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 99:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 100:   0%|          | 0/5 [00:00<?, ?it/s]

psalms 101:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 102:   0%|          | 0/28 [00:00<?, ?it/s]

psalms 103:   0%|          | 0/22 [00:00<?, ?it/s]

psalms 104:   0%|          | 0/35 [00:00<?, ?it/s]

psalms 105:   0%|          | 0/45 [00:00<?, ?it/s]

psalms 106:   0%|          | 0/48 [00:00<?, ?it/s]

psalms 107:   0%|          | 0/43 [00:00<?, ?it/s]

psalms 108:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 109:   0%|          | 0/31 [00:00<?, ?it/s]

psalms 110:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 111:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 112:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 113:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 114:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 115:   0%|          | 0/18 [00:00<?, ?it/s]

psalms 116:   0%|          | 0/19 [00:00<?, ?it/s]

psalms 117:   0%|          | 0/2 [00:00<?, ?it/s]

psalms 118:   0%|          | 0/29 [00:00<?, ?it/s]

psalms 119:   0%|          | 0/176 [00:00<?, ?it/s]

psalms 120:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 121:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 122:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 123:   0%|          | 0/4 [00:00<?, ?it/s]

psalms 124:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 125:   0%|          | 0/5 [00:00<?, ?it/s]

psalms 126:   0%|          | 0/6 [00:00<?, ?it/s]

psalms 127:   0%|          | 0/5 [00:00<?, ?it/s]

psalms 128:   0%|          | 0/6 [00:00<?, ?it/s]

psalms 129:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 130:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 131:   0%|          | 0/3 [00:00<?, ?it/s]

psalms 132:   0%|          | 0/18 [00:00<?, ?it/s]

psalms 133:   0%|          | 0/3 [00:00<?, ?it/s]

psalms 134:   0%|          | 0/3 [00:00<?, ?it/s]

psalms 135:   0%|          | 0/21 [00:00<?, ?it/s]

psalms 136:   0%|          | 0/26 [00:00<?, ?it/s]

psalms 137:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 138:   0%|          | 0/8 [00:00<?, ?it/s]

psalms 139:   0%|          | 0/24 [00:00<?, ?it/s]

psalms 140:   0%|          | 0/13 [00:00<?, ?it/s]

psalms 141:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 142:   0%|          | 0/7 [00:00<?, ?it/s]

psalms 143:   0%|          | 0/12 [00:00<?, ?it/s]

psalms 144:   0%|          | 0/15 [00:00<?, ?it/s]

psalms 145:   0%|          | 0/21 [00:00<?, ?it/s]

psalms 146:   0%|          | 0/10 [00:00<?, ?it/s]

psalms 147:   0%|          | 0/20 [00:00<?, ?it/s]

psalms 148:   0%|          | 0/14 [00:00<?, ?it/s]

psalms 149:   0%|          | 0/9 [00:00<?, ?it/s]

psalms 150:   0%|          | 0/6 [00:00<?, ?it/s]

ruth 1:   0%|          | 0/22 [00:00<?, ?it/s]

ruth 2:   0%|          | 0/23 [00:00<?, ?it/s]

ruth 3:   0%|          | 0/18 [00:00<?, ?it/s]

ruth 4:   0%|          | 0/22 [00:00<?, ?it/s]

songs 1:   0%|          | 0/17 [00:00<?, ?it/s]

songs 2:   0%|          | 0/17 [00:00<?, ?it/s]

songs 3:   0%|          | 0/11 [00:00<?, ?it/s]

songs 4:   0%|          | 0/16 [00:00<?, ?it/s]

songs 5:   0%|          | 0/16 [00:00<?, ?it/s]

songs 6:   0%|          | 0/13 [00:00<?, ?it/s]

songs 7:   0%|          | 0/13 [00:00<?, ?it/s]

songs 8:   0%|          | 0/14 [00:00<?, ?it/s]

zechariah 1:   0%|          | 0/21 [00:00<?, ?it/s]

zechariah 2:   0%|          | 0/13 [00:00<?, ?it/s]

zechariah 3:   0%|          | 0/10 [00:00<?, ?it/s]

zechariah 4:   0%|          | 0/14 [00:00<?, ?it/s]

zechariah 5:   0%|          | 0/11 [00:00<?, ?it/s]

zechariah 6:   0%|          | 0/15 [00:00<?, ?it/s]

zechariah 7:   0%|          | 0/14 [00:00<?, ?it/s]

zechariah 8:   0%|          | 0/23 [00:00<?, ?it/s]

zechariah 9:   0%|          | 0/17 [00:00<?, ?it/s]

zechariah 10:   0%|          | 0/12 [00:00<?, ?it/s]

zechariah 11:   0%|          | 0/17 [00:00<?, ?it/s]

zechariah 12:   0%|          | 0/14 [00:00<?, ?it/s]

zechariah 13:   0%|          | 0/9 [00:00<?, ?it/s]

zechariah 14:   0%|          | 0/21 [00:00<?, ?it/s]

zephaniah 1:   0%|          | 0/18 [00:00<?, ?it/s]

zephaniah 2:   0%|          | 0/15 [00:00<?, ?it/s]

zephaniah 3:   0%|          | 0/20 [00:00<?, ?it/s]